spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=query
    username: postgres
    password: example
  jpa:
    hibernate:
      base-jpa:
        generator: org.hibernate.id.enhanced.SequenceStyleGenerator
    database: postgresql
    show-sql: true
server:
  port: 8080